import Header from "@/components/Header";
import { ThemeProvider } from "@/components/theme-provider";
import Link from "next/link";
import {
  BookText,
  Video,
  MessageCircle,
  ArrowLeftToLine,
  GraduationCap,
  UserRound,
} from "lucide-react";
import { Button } from "@/components/ui/button";
import { NextSSRPlugin } from "@uploadthing/react/next-ssr-plugin";
import { extractRouterConfig } from "uploadthing/server";
import { ourFileRouter } from "@/app/api/uploadthing/core";

export const metadata = {
  title: "Classes",
  description: "Generated by Bessbess",
};

export default function RootLayout({ children, params }) {
  const url = params.classes.split("%20");
  const classcode = url[0];
  return (
    <main>
      <NextSSRPlugin routerConfig={extractRouterConfig(ourFileRouter)} />
      <ThemeProvider attribute="class" enableSystem>
        <Header />
        <div className="flex gap-2">
          <nav className=" flex flex-col sm:items-start items-center gap-6  sm:w-[200px] w-[100px] min-h-svh p-2 pt-6 shadow-md dark:bg-black/20 drop-shadow-lg">
            <Link
              title="chat"
              href={`/${params.classes}/chat`}
              className=" gap-2 flex items-center gap shadow-md hover:shadow-lg transition-all font-semibold  dark:bg-white dark:text-black  p-2 rounded-lg sm:w-full w-fit"
            >
              <MessageCircle />
              <span className="sm:inline-block hidden">chat With Ai</span>
            </Link>
            <Link
              title="video call"
              href={`/meet/${classcode}`}
              className=" gap-2 flex items-center gap shadow-md hover:shadow-lg transition-all font-semibold  dark:bg-white dark:text-black  p-2 rounded-lg sm:w-full w-fit"
            >
              <Video />
              <span className="sm:inline-block hidden">Meet</span>
            </Link>
            <Link
              title="documents"
              href={`/${params.classes}/docs`}
              className=" gap-2 flex items-center gap shadow-md hover:shadow-lg transition-all font-semibold  dark:bg-white dark:text-black  p-2 rounded-lg sm:w-full w-fit"
            >
              <BookText />
              <span className="sm:inline-block hidden">Documents</span>
            </Link>
            <Link
              title="teachers"
              href={`/${params.classes}/teachers`}
              className=" gap-2 flex items-center gap shadow-md hover:shadow-lg transition-all font-semibold  dark:bg-white dark:text-black  p-2 rounded-lg sm:w-full w-fit"
            >
              <GraduationCap />
              <span className="sm:inline-block hidden">Teachers</span>
            </Link>
            <Link
              title="teachers"
              href={`/${params.classes}/students`}
              className=" gap-2 flex items-center gap shadow-md hover:shadow-lg transition-all font-semibold  dark:bg-white dark:text-black  p-2 rounded-lg sm:w-full w-fit"
            >
              <UserRound />
              <span className="sm:inline-block hidden">students</span>
            </Link>
            <Button>
              <Link
                title="dashboard"
                href={`/account`}
                className="flex gap-1 items-center"
              >
                <ArrowLeftToLine />
                <span className=" underline lg:inline hidden">
                  Back to Dashboard
                </span>
              </Link>
            </Button>
          </nav>
          {children}
        </div>
      </ThemeProvider>
    </main>
  );
}
