import Header from "@/components/Header";
import { ThemeProvider } from "@/components/theme-provider";
import Link from "next/link";
import {
  BookText,
  Video,
  MessageCircle,
  ArrowLeftToLine,
  GraduationCap,
  UserRound,
} from "lucide-react";
import { Button } from "@/components/ui/button";

export const metadata = {
  title: "Classes",
  description: "Generated by Bessbess",
};

export default function RootLayout({ children, classes }) {
  return (
    <main>
      <ThemeProvider attribute="class" enableSystem>
        <Header />
        <div className="flex gap-2">
          <nav className=" flex flex-col sm:items-start items-center gap-6  w-[20%] min-h-svh p-2 pt-6 shadow-md dark:bg-black/20 drop-shadow-lg">
            <Link
              title="chat"
              href={`/${classes}/chat`}
              className=" gap-2 flex items-center gap shadow-md hover:shadow-lg transition-all font-semibold  dark:bg-white dark:text-black  p-2 rounded-lg sm:w-full w-fit"
            >
              <MessageCircle />
              <span className="sm:inline-block hidden">chat</span>
            </Link>
            <Link
              title="video call"
              href={`/meet`}
              className=" gap-2 flex items-center gap shadow-md hover:shadow-lg transition-all font-semibold  dark:bg-white dark:text-black  p-2 rounded-lg sm:w-full w-fit"
            >
              <Video />
              <span className="sm:inline-block hidden">Meet</span>
            </Link>
            <Link
              title="documents"
              href={`/${classes}/docs`}
              className=" gap-2 flex items-center gap shadow-md hover:shadow-lg transition-all font-semibold  dark:bg-white dark:text-black  p-2 rounded-lg sm:w-full w-fit"
            >
              <BookText />
              <span className="sm:inline-block hidden">Documents</span>
            </Link>
            <Link
              title="teachers"
              href={`/${classes}/teachers`}
              className=" gap-2 flex items-center gap shadow-md hover:shadow-lg transition-all font-semibold  dark:bg-white dark:text-black  p-2 rounded-lg sm:w-full w-fit"
            >
              <GraduationCap />
              <span className="sm:inline-block hidden">Teachers</span>
            </Link>
            <Link
              title="teachers"
              href={`/${classes}/students`}
              className=" gap-2 flex items-center gap shadow-md hover:shadow-lg transition-all font-semibold  dark:bg-white dark:text-black  p-2 rounded-lg sm:w-full w-fit"
            >
              <UserRound />
              <span className="sm:inline-block hidden">students</span>
            </Link>
            <Button>
              <Link
                title="dashboard"
                href={`/account`}
                className="flex gap-1 items-center"
              >
                <ArrowLeftToLine />
                <span className=" underline sm:inline hidden">
                  {" "}
                  Go Back to Dashboard
                </span>
              </Link>
            </Button>
          </nav>
          {children}
        </div>
      </ThemeProvider>
    </main>
  );
}
